[platformio]
default_envs = jc1060

[env:jc1060]
platform = https://github.com/pioarduino/platform-espressif32.git#53.03.13+github
framework = arduino
board = esp32-p4-evboard
board_build.psram = enabled
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_deps =
    lvgl/lvgl@^9.2.2
    bblanchon/ArduinoJson@^7.0.0
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I .
    -I src
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
